development:
  adapter: mysql2
  database: penciLab_development
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: penciLab_test
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: penciLab_production
  pool: 5
  timeout: 5000
